objtool/disas.c: Fix build failure due to printf macro
disas.c:112:9: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘bfd_vma’ {aka ‘unsigned int’} [-Werror=format=]
  112 |         __builtin_choose_expr(sizeof(bfd_vma) == sizeof(unsigned long), "%#lx <%s>", "%#llx <%s>")
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
disas.c:110:52: note: in definition of macro ‘DINFO_FPRINTF’
  110 |         ((*(dinfo)->fprintf_func)((dinfo)->stream, __VA_ARGS__))
      |                                                    ^~~~~~~~~~~
disas.c:175:38: note: in expansion of macro ‘bfd_vma_fmt’
  175 |                 DINFO_FPRINTF(dinfo, bfd_vma_fmt, addr, symstr);
      |                                      ^~~~~~~~~~~